=== gaurav324/English-Lexicalized-Text-Substituion/TaskTestData/test/lexsub.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>
<!ELEMENT corpus (lexelt+)>
<!ATTLIST corpus lang CDATA #REQUIRED>

<!ELEMENT lexelt (instance+)>
<!ATTLIST lexelt item CDATA #REQUIRED>

<!ELEMENT instance (context)>
<!ATTLIST instance id CDATA #REQUIRED>

<!ELEMENT context (#PCDATA | head)*>
<!ELEMENT head (#PCDATA)>

=== gaurav324/English-Lexicalized-Text-Substituion/TaskTestData/trial/lexsub_trial_cleaned.xml
<?xml version="1.0" ?>
<!DOCTYPE corpus SYSTEM "lexsub.dtd">

<corpus lang="english">
	<lexelt item="bright.a">
		<instance id="1">
			<context>During the siege , George Robertson had appointed Shuja-ul-Mulk , who was a _START_bright_END_ boy only 12 years old and the youngest surviving son of Aman-ul-Mulk , as the ruler of Chitral .</context>
		</instance>
		<instance id="2">
			<context>The actual field is not much different than that of a 40mm , only it is smaller and quite a bit noticeably _START_brighter_END_ , which is probably the main benefit .</context>
		</instance>
		<instance id="3">
			<context>The roses have grown out of control , wild and carefree , their _START_bright_END_ blooming faces turned to bathe in the early autumn sun .</context>
		</instance>
		<instance id="4">
			<context>He was _START_bright_END_ and independent and proud .</context>
		</instance>
		<instance id="5">
			<context>In fact , during at least six distinct periods in Army history since World War I , lack of trust and confidence in senior leaders caused the so-called best and _START_brightest_END_ to leave the Army in droves .</context>
		</instance>
		<instance id="6">
			<context>An evening of classical symphonic music , played by the next generation stars in the American orchestral scene , can be savored at the New World Symphony , a special Miami institution that nurtures the best and _START_brightest_END_ young symphonic musicians .</context>
		</instance>
		<instance id="7">
			<context>There are sound reasons for concluding that the long-run picture remains _START_bright_END_ , and even recent signals about the current course of the economy have turned from unremittingly negative through the late fall of last year to a far more mixed set of signals recently .</context>
		</instance>
		<instance id="8">
			<context>Snow covered areas appear _START_bright_END_ blue in the image which was taken in early spring and shows deep snow cover .</context>
		</instance>
		<instance id="9">
			<context>She turns eyes _START_bright_END_ with excitement towards Fiona , still tugging on the string of the minitiature airship-cum-dance card she has just received at the door .</context>
		</instance>
		<instance id="10">
			<context>A short excerpt : I was praying in private until someone got the _START_bright_END_ idea of starting a Presidential Prayer Team .</context>
		</instance>
	</lexelt>
	<lexelt item="film.n">
		<instance id="11">
			<context>So , unlike studio films , independent _START_films_END_ cannot be conceptually geared to a marketing campaign , or used to recruit merchandising tie-ins .</context>
		</instance>
		<instance id="12">
			<context>The packed screening of about 100 high-level press people loved the _START_film_END_ as well .</context>
		</instance>
		<instance id="13">
			<context>I think most filmmakers for the most part right now they&#8217;re thinking about the DVD when they go in to production because the reality is DVD is where the great majority of your audience is going to experience the _START_film_END_ .</context>
		</instance>
		<instance id="14">
			<context>Dune makes the second Lynch _START_film_END_ to be released in a consumer HD format ( Mulholland Drive on D-VHS being the first ) .</context>
		</instance>
		<instance id="15">
			<context>Film Music Literature Cyberplace - Includes _START_film_END_ reviews , message boards , chat room , and images from various films .</context>
		</instance>
		<instance id="16">
			<context>His feature _START_film_END_ debut HEROES / DE STÃRSTE HELTE ( 1996 ) won awards at Rouen and Madrid .</context>
		</instance>
		<instance id="17">
			<context>( Some people keep their TVs on for company. ) In Malta , news is the main reason we turn to TV , followed by _START_films_END_ , talk shows , documentaries , serials , and music , in that order .</context>
		</instance>
		<instance id="18">
			<context>The _START_film_END_ shows Afghan mercenaries to be involved with the separatists , suggesting that the present struggle in Kashmir has been hijacked by foreign extremists , who are shown discussing the loss of Bangladesh in the 1971 war , providing it as a justification for their present acts of revenge .</context>
		</instance>
		<instance id="19">
			<context>A fine score by George Fenton ( THE CRUCIBLE ) and beautiful photograhy by Roger Pratt add greatly to the effectiveness of the _START_film_END_ .</context>
		</instance>
		<instance id="20">
			<context>The success of Autry &apos; s early _START_films_END_ was not enough to save Mascot Pictures , which collapsed under the weight of debts held by Consolidated Film Laboratories , which did Mascot &apos;s film processing .</context>
		</instance>
	</lexelt>
	<lexelt item="take.v">
		<instance id="21">
			<context>That &apos;s not to say the process of actual negotiating is n&apos;t _START_taking_END_ place .</context>
		</instance>
		<instance id="22">
			<context>&quot; Hugh Grant and Alan Rickman , as Edward and Col. Brandon respectively , _START_took_END_ the most chances and the various reviewers therefore either love or hate their performances .</context>
		</instance>
		<instance id="23">
			<context>It should n&apos;t _START_take_END_ that long .</context>
		</instance>
		<instance id="24">
			<context>It only affects the start up time of a program , and for a process that _START_takes_END_ several months ( his code was computing the 196 Palindrome Quest ) , it does not matter if the initialization code takes 1/1,000th of a second or 1/10,000th of a second .</context>
		</instance>
		<instance id="25">
			<context>If we _START_take_END_ the factual context in which the term is used into consideration , then its extension becomes limited , owing to the context .</context>
		</instance>
		<instance id="26">
			<context>If you do n&apos;t _START_take_END_ the risk of dying by driving to the store , your house could collapse on you and kill you anyway .</context>
		</instance>
		<instance id="27">
			<context>The Governor _START_took_END_ the big sheets of imitation parchment , glanced over them , signed his name to each , laid down the pen , and handed the papers across the table to Dreier .</context>
		</instance>
		<instance id="28">
			<context>O&apos;Neill and the two men who worked under his supervision maintained the avenue , raking the thin gravel and removing any weed that tried to _START_take_END_ root in the stony earth .</context>
		</instance>
		<instance id="29">
			<context>Even if the Anglo-French Summit did not _START_take_END_ place until next year , the Prime Minister and President Chirac were still due to see each other in November and December .</context>
		</instance>
		<instance id="30">
			<context>40 Day-to-day financial and operational management is the responsibility of the Chief Officer , who _START_took_END_ up her post in June 2001 .</context>
		</instance>
	</lexelt>
	<lexelt item="tight.r">
		<instance id="31">
			<context>Anyway , my pants are getting _START_tight_END_ .</context>
		</instance>
		<instance id="32">
			<context>With the physical market has _START_tight_END_ as it has been in memory , silver could fly at any time .</context>
		</instance>
		<instance id="33">
			<context>More ... Specialty coffee market quiet , supplies _START_tight_END_ Posted at 2:57 PM by Robert Badgett By Bruce Kamich NEW YORK , June 6 ( Reuters ) - Specialty coffee dealers said on Friday that business was unusually quiet with most retailers &apos; sales numbers down from a year ago , but prices for choice beans remained firm with supplies short until the next crops become available .</context>
		</instance>
		<instance id="34">
			<context>If your money is _START_tight_END_ do n&apos;t cut corners .</context>
		</instance>
		<instance id="35">
			<context>Each child lies inside an Isolette incubator , a clear acrylic rectangle with ample room for a half-sized premature baby , though the quarters become _START_tight_END_ for the full-term eight-pounders .</context>
		</instance>
		<instance id="36">
			<context>&quot; It can be intimidating at first , because they wrap their arms pretty _START_tight_END_ around you , and everything they latch onto is pretty much headed straight to their mouth , &quot; Schmitz said .</context>
		</instance>
		<instance id="37">
			<context>The incisions will feel _START_tight_END_ for the first 24-48 hours .</context>
		</instance>
		<instance id="38">
			<context>Except for the soldiers , Goth was locked up _START_tight_END_ .</context>
		</instance>
		<instance id="39">
			<context>Nathan Robins : Did well to keep _START_tight_END_ on the Left winger and was harshly judged by the referee on several occasions to have fouled the opposing player when I felt he just out muscled him .</context>
		</instance>
		<instance id="40">
			<context>I know that the market is _START_tight_END_ right now .</context>
		</instance>
	</lexelt>
	<lexelt item="bar.n">
		<instance id="41">
			<context>That &apos;s not a very high _START_bar_END_ .</context>
		</instance>
		<instance id="42">
			<context>This more upright position is most easily and affordably achieved through slapping a riser bar on your setup , and only requires you to buy a bar instead of a _START_bar_END_ and stem .</context>
		</instance>
		<instance id="43">
			<context>For twelve hours Livewire will be broadcasting live from the blue _START_bar_END_ of Union House at UEA in an attempt to raise as much money as possible for a very worthy cause .</context>
		</instance>
		<instance id="44">
			<context>The British government imposed a colour _START_bar_END_ in its colonies , so young blacks went in only for law or medicine where they could make a living without government support .</context>
		</instance>
		<instance id="45">
			<context>Put granola _START_bars_END_ in bowl .</context>
		</instance>
		<instance id="46">
